name: Sync to hugging face
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions Tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://swastik1717:$HF@huggingface.co/spaces/swastik1717/my-first-space
        
      - name: Push to Hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force space main
