name: Sync to hugging face
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Push to Hub
        uses: naterush/huggingface-spaces-auth-action@v1
        with:
          token: ${{ secrets.HF }}
          space_id: swastik1717/my-first-space
